use std::path::Path;

fn main() {
    // Ensure the placeholder certificate resource exists so tauri-build
    // doesn't fail on a fresh clone (the real cert is generated by sign.ps1).
    let cer_path = Path::new("../resources/sidearm-ca.cer");
    if !cer_path.exists() {
        if let Some(parent) = cer_path.parent() {
            let _ = std::fs::create_dir_all(parent);
        }
        let _ = std::fs::write(cer_path, b"");
    }

    let windows = tauri_build::WindowsAttributes::new()
        .app_manifest(include_str!("manifest.xml"));
    let attrs = tauri_build::Attributes::new().windows_attributes(windows);
    tauri_build::try_build(attrs).expect("failed to run tauri build script");
}
